#pragma once

#include <cstdint>

namespace glcompat {

// OpenGL error codes surfaced by the frontend. Backend-native errors are
// translated into these OpenGL-visible semantics (SPEC §19), never passed
// through verbatim.
enum class GLError : uint32_t {
    NoError = 0,
    InvalidEnum,
    InvalidValue,
    InvalidOperation,
    InvalidName,    // name not generated by the frontend
    OutOfMemory,
    NoCurrentContext,
    StackUnderflow, // pop with empty stack (e.g. glPopDebugGroup)
    StackOverflow   // push beyond MAX_DEBUG_GROUP_STACK_DEPTH
};

} // namespace glcompat
