#!/usr/bin/env python3
"""Generate extern "C" GL wrappers that forward YAGLT's public OpenGL API
(glcompat::gl*) to plain C `gl*` symbols.

This lets the EGL drop-in shim (src/egl_shim) export the full desktop GL 4.6
surface as C symbols, so an unmodified application that links/loads libEGL and
calls `gl*` directly actually invokes YAGLT's frontend.

The source of truth is include/glcompat/frontend/gl_api.hpp; re-running this
script re-syncs the generated file, so the GL surface is never hand-maintained.
"""
import re
import sys

HEADER = """// AUTO-GENERATED by tools/gen_gl_exports.py -- do not edit by hand.
// Forwards YAGLT's public OpenGL frontend (glcompat::gl*) onto C `gl*` symbols
// so the EGL drop-in shim can export the desktop GL surface.
//
// These wrappers live at global scope with C linkage so they do NOT collide with
// the C++-linkage glcompat::gl* declarations in gl_api.hpp; each simply calls the
// qualified glcompat:: implementation.

#include "glcompat/frontend/gl_api.hpp"

// Pull the GL scalar/type aliases into the global scope so the C wrappers below
// can name them (the glcompat:: function names themselves are NOT imported, to
// avoid clashing with the C++-linkage glcompat::gl* declarations).
using glcompat::GLenum;
using glcompat::GLuint;
using glcompat::GLsizei;
using glcompat::GLint;
using glcompat::GLsizeiptr;
using glcompat::GLintptr;
using glcompat::GLfloat;
using glcompat::GLdouble;
using glcompat::GLvoid;
using glcompat::GLchar;
using glcompat::GLboolean;
using glcompat::GLbitfield;
using glcompat::GLubyte;
using glcompat::GLbyte;
using glcompat::GLshort;
using glcompat::GLushort;
using glcompat::GLuint64;
using glcompat::GLint64;
using glcompat::GLsync;
using glcompat::GLDEBUGPROC;
"""

FOOTER = ""


def strip_comments(text):
    text = re.sub(r"/\*.*?\*/", " ", text, flags=re.DOTALL)
    text = re.sub(r"//[^\n]*", " ", text)
    return text


def split_params(args):
    """Split a parameter list on top-level commas."""
    out = []
    depth = 0
    cur = ""
    for ch in args:
        if ch == "," and depth == 0:
            out.append(cur)
            cur = ""
        else:
            if ch == "(":
                depth += 1
            elif ch == ")":
                depth -= 1
            cur += ch
    if cur.strip():
        out.append(cur)
    return out


def param_name(p):
    p = p.strip()
    if not p:
        return None
    # drop a default value if present
    p = p.split("=")[0].strip()
    # the name is the final identifier (after stripping pointer/ref markers)
    tokens = p.replace("*", " ").replace("&", " ").split()
    # filter out pure type tokens; keep the last plausible identifier
    name = None
    for t in tokens:
        if re.match(r"^[A-Za-z_]\w*$", t):
            name = t
    return name


def main():
    if len(sys.argv) != 3:
        sys.stderr.write("usage: gen_gl_exports.py <gl_api.hpp> <out.cpp>\n")
        return 1
    src_path, out_path = sys.argv[1], sys.argv[2]
    with open(src_path) as f:
        text = strip_comments(f.read())

    # Match free function declarations: RET glName(ARGS);
    pat = re.compile(
        r"([A-Za-z_][\w\s\*]*?)\s+((?:gl|glX)[A-Za-z0-9_]+)\s*\(([\s\S]*?)\)\s*;",
        re.DOTALL,
    )

    funcs = []
    for m in pat.finditer(text):
        ret = m.group(1).strip()
        name = m.group(2)
        args = m.group(3).strip()
        # skip obvious non-gl or empty return (defensive)
        if not name.startswith("gl"):
            continue
        if ret == "":
            continue
        params = split_params(args)
        # A lone "void" parameter means no arguments; emit a parameterless call.
        if len(params) == 1 and params[0].strip() == "void":
            params = []
        names = []
        decls = []
        for i, p in enumerate(params):
            pn = param_name(p)
            if pn is None:
                pn = "a%d" % i
            names.append(pn)
            decls.append(p.strip())
        # Skip C++-only overloads (e.g. a std::string convenience variant); the
        # canonical C signature (if present) is still exported. C cannot mangle
        # overloads, and std:: types are not C-compatible.
        if "std::" in ret or any("std::" in d for d in decls):
            continue
        funcs.append((ret, name, decls, names))

    # de-duplicate (a name could appear once only in this header)
    seen = set()
    out = [HEADER]
    for ret, name, decls, names in funcs:
        if name in seen:
            continue
        seen.add(name)
        argdecl = ", ".join(decls) if decls else "void"
        argcall = ", ".join(names)
        if ret.strip() == "void":
            body = "    ::glcompat::%s(%s);\n" % (name, argcall)
        else:
            body = "    return ::glcompat::%s(%s);\n" % (name, argcall)
        out.append(
            "extern \"C\" %s %s(%s) {\n%s}\n" % (ret, name, argdecl, body)
        )

    with open(out_path, "w") as f:
        f.write("\n".join(out))
    sys.stderr.write("gen_gl_exports: wrote %d GL wrappers\n" % len(funcs))
    return 0


if __name__ == "__main__":
    sys.exit(main())
